# Generated by Django 4.2.5 on 2023-09-13 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IHA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="Marka")),
                ("model_name", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "cruising_speed",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Seyir Hızı (mach)"
                    ),
                ),
                (
                    "max_speed",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Maksimum Hız (mach)",
                    ),
                ),
                ("flight_duration", models.DurationField(verbose_name="Uçuş Süresi")),
                (
                    "max_payload_capacity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Maksimum Yük Kapasitesi (kilogram)",
                    ),
                ),
                (
                    "operational_altitude",
                    models.CharField(max_length=100, verbose_name="Operasyonel İrtifa"),
                ),
                ("iha_type", models.CharField(max_length=50, verbose_name="İHA Türü")),
                ("production_date", models.DateField(verbose_name="Üretim Tarihi")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Aktif"), ("rented", "Bakımda")],
                        default="active",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHAUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rental_date_start",
                    models.DateField(verbose_name="Kiralama Tarihi Başlangıç"),
                ),
                (
                    "rental_date_end",
                    models.DateField(verbose_name="Kiralama Tarihi Bitiş"),
                ),
                (
                    "iha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="iha.iha",
                        verbose_name="Kiralanan İHA",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kiralayan Üye",
                    ),
                ),
            ],
        ),
    ]
