# Generated by Django 4.2.5 on 2023-09-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="iha",
            name="slug",
            field=models.CharField(default="deneme", max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
