# Generated by Django 4.2.5 on 2023-09-13 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0002_iha_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iha",
            name="iha_type",
        ),
    ]
