# Generated by Django 4.2.5 on 2023-09-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0003_remove_iha_iha_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iha",
            name="flight_duration",
            field=models.DurationField(verbose_name="Uçuş Süresi (saat)"),
        ),
        migrations.AlterField(
            model_name="iha",
            name="max_payload_capacity",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=7,
                verbose_name="Maksimum Yük Kapasitesi (kilogram)",
            ),
        ),
        migrations.AlterField(
            model_name="iha",
            name="operational_altitude",
            field=models.CharField(
                max_length=100, verbose_name="Operasyonel İrtifa (feet)"
            ),
        ),
        migrations.AlterField(
            model_name="iha",
            name="status",
            field=models.CharField(
                choices=[("active", "Aktif"), ("rented", "Kiralandı")],
                default="active",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
