# Generated by Django 4.2.5 on 2023-09-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0004_alter_iha_flight_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iha",
            name="flight_duration",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Uçuş Süresi (saat)"
            ),
        ),
    ]
