# Generated by Django 4.2.5 on 2023-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iha", "0005_alter_iha_flight_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iha",
            name="brand",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Marka"
            ),
        ),
        migrations.AlterField(
            model_name="iha",
            name="model_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Model"
            ),
        ),
    ]
