# Generated by Django 4.2.5 on 2023-09-16 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("iha", "0008_useractions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractions",
            name="iha",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="iha.iha"
            ),
        ),
        migrations.AlterField(
            model_name="useractions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
